### ISSUE TITLE
Mobile: Video Calls - Research

### ISSUE THREAD

**Issue by trentstauff** [Team-uMigrate/umigrate#114]
We must do further research on implementing Video Calls with WebRTC.

See https://docs.google.com/document/d/179vcJzIopOyYzaG3HlH7yqjXgsF74L61HRmxOK1wvMQ/edit
for more information. This task is low priority (in comparison to the other tasks)

**Comment by deandrebaker** [comment]
Closing this issue because we don't know if we want to keep it in for this term
