### ISSUE TITLE
UI-Design: Create login/registration page for mobile

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#117]
We need to have a framer prototype for the Login and Registration page for the mobile app. Here are the specifications for each.

Login page
- Requires email and password
- A Login button
- A button used for going to the Registration page

Registration page
- Requires email, password, and confirm password (password a second time)
- A button that will send the user an email with a link to complete registration (not sure what we wanna call this button)
- A button used for going back to the Login page

We may want to add something umigratey at the top (like a banner or something). Up to the assignee to figure out if it's necessary)

**Comment by dharinirajah** [comment]
@illyat Can we add screenshots to any issue when it's complete (as we aren't a team tracking via code, it's important to track the appearance of the app)?
