### ISSUE TITLE
UI-Design: Create menu page for mobile

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#137]
We need to have a prototype for the mobile menu page. The menu page should have the following sections (for now): 
- Profile
- Notification settings
- Blocking

This issue does not require you to add any content within the profile section. We can add placeholders for now

**Comment by dharinirajah** [comment]
After meeting on 9/30/2020 : 
![image](https://user-images.githubusercontent.com/52252036/94759263-3ff3a380-0354-11eb-8ab5-ab6de7906e11.png)

**Comment by adrian-salvador** [comment]
looks good :)
