### ISSUE TITLE
UI-Design: Create messaging (chat selection) page for mobile

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#139]
We need to make a prototype for the messaging page where the user can select who they want to chat with. We want to have a search mechanism where users can search for other users they have chatted with or can chat with. Within each item on this page, we need a way to indicate whether there is a new message in that chat or not. We also want a image of the user they are chatting it within each item. 

For now, assume we are not doing group chats.

**Comment by dharinirajah** [comment]
@denlee973 Make sure to have/not have the following in the Messaging Page.

- What information should be on a message?
- - Content
- - The creator
- - The time
- - Like reactions
- What can we do with messages?
- - Like
- Can we edit/delete messages?
- - No edits
- - No delete messages
- Should rooms have admins? If so, what can an admin do?
- - No admins


Do we need more information from PDT?

**Comment by denlee973** [comment]
Selecting chat:
![image](https://user-images.githubusercontent.com/16948515/94328269-0ea75c00-ff7f-11ea-90b4-8e965a684a43.png)
Messaging page once chat is selected:
![image](https://user-images.githubusercontent.com/16948515/94328379-10bdea80-ff80-11ea-93f4-4df75345b829.png)

File exists for group messaging but assuming group messages do not exist.
