### ISSUE TITLE
API: Support photo collections for postings

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#207]
When the user creates a posting, we want to allow them to upload multiple photos for a single posting. These photos should also be returned in the JSON response for the posting.

Sub-tasks: 
- Develop a plan and share it with the team
- Modify the 'GenericPhotoCollectionModel' to support multiple photos (most likely will require a many-to-one relationship)
- Update the posting models with the changes made to the 'GenericPhotoCollectionModel'
- Create a serializer class for an image object if many-to-one relationships are used.
- Create endpoints for uploading images if necessary.

Notes:
- Investigate if there are already any third-party packages that can already do this
- We may have to refactor how the API automatically deletes photos (look at the GenericPhotoModel class in generic_models.py)

**Comment by Terence-Wong** [comment]
Check for packages for multiimage models, if none good, use separate image endpoint for each posting
