### ISSUE TITLE
UI-Design : Create User Profile Modal View

### ISSUE THREAD

**Issue by dharinirajah** [Team-uMigrate/umigrate#222]
When you click on a user's profile (through liked users, messages, notifications, posts, comments, etc.,) a modal should come up with the intro information for the users. Name, profile pic, banner, year, major. You can then have the option to connect with them or go further to view their profile.

**Comment by arshahluwalia** [comment]
<img width="595" alt="Screen Shot 2020-10-05 at 10 26 36 PM" src="https://user-images.githubusercontent.com/54185054/95151904-d6abd000-0759-11eb-8ff3-fb9e74b5fa60.png">
