### ISSUE TITLE
Cloud-Ops: Move scripts to */deployments folders

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#232]
The */deployments folders should contain the scripts that will be executed in the release pipelines. We need to move the infrastructure scripts folder into the deployment folder, and create scripts for the api and website release pipelines.

Sub-tasks:
- Move the scripts from /infrastructure/src/scripts into /infrastructure/deployments/scripts
- Create scripts for the API release pipeline tasks
- Create scripts for the Website release pipeline tasks
- Modify the build pipelines to copy the scripts folder to the drop folder (we should not have to modify the release pipelines if done correctly)
- Test all releases to dev and ensure they work correctly

**Comment by adrian-salvador** [comment]
@adrian-salvador redis script :)
