### ISSUE TITLE
API: Improve saved, liked, interested, and attending postings endpoints

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#279]
We should create an abstract class API view that renders a list of postings on a get request, and on a post request it accepts a json object with id of the posting and a boolean flag indicating whether to save, like, etc. a posting or not. It should use the data in the json object to add the user to the list of saved users, liked users, etc. for that posting.

We also need to remember to right tests for this.

**Comment by Terence-Wong** [comment]
- To get a list of posts you've saved OR to save a post, you go to the /api/posts/saved endpoint
- Same pattern above for all liked postings and for interested/attending events

**Comment by Terence-Wong** [comment]
add post request for liking postings, change app_label, add tests
