### ISSUE TITLE
API: SerializerMethodField for likes, poll votes, and other fields

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#29]
On the post, event, ad, listing, and comment models, we need a field for storing the total number of likes. Additionally, when a user likes one of these resources, it increases the number of likes (decreases if the user unlikes). We can modify this filed of the resource by using SerializerMethodField in the serializers classes. For more information on the SerializerMethodField, check out https://www.django-rest-framework.org/api-guide/fields/.

**Comment by bringuy** [comment]
https://www.linkedin.com/learning/building-restful-web-apis-with-django/serializer-that-shows-model-relationships?u=55034593

Chapter 3 part 2
