### ISSUE TITLE
Cloud-Ops: Upgrade redis to version 6.0.9

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#300]
We need to upgrade redis to version 6.0.x on the server through our pipelines.

**Comment by adrian-salvador** [comment]
CHECK version of redis on new server

**Comment by adrian-salvador** [comment]
_we want to uninstall redis first_
sudo apt-get purge --auto-remove redis-server 

**biggest thing is to do the upgrade !!**
sudo apt-get update
sudo apt-get upgrade

_THEN install redis_
sudo apt-get install redis-server
