### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#400]
We want to allow users to set their notification preferences. We should have a setting for each type of notification, and we should check that we only send notifications to users who have the corresponding setting set to 'on'

**Comment by NihalPotdar** [comment]
API: Reactor code to support notification preferences

    1) Refactor the users model to support an array field of notification preferences
  
    - The choices for this field should be `tagged` (when the user is tagged in a shared item),
    `comment` (when another user comments on a shared item), `connection_request` (when a user receives a connection request),
    `like` (when a user receives a like on a shared item)
    - The field should be initialized to all of the choices by default
  
    The users model is in \users\models.py, and be sure to make edits
    to any other field to support this change
  
    2) Create a new field in the notifications table to support a notification type,
    the notification type and should only be one of the above choices. Be sure to make any
    corresponding changes to \notification to support this change

API: Add feature to send only certain notifications to users

  The goal of this ticket is to send users only the notifications that they have subscribed to.
  In the user model, there should be a field for notification preferences and each notification
  should have a notification type. We still want users to be able to access notifications
  that they have missed when they change their notification preferences.

  1) Modify NotificationList in \notifications\api_views.py and any related functions to
  ensure that a notification is only sent out when user's preferences is set to include that notification type

App: Create notification preferences form

  Create a basic form based on the designs from the UI team which consists of a series of choices for notification preferences
    - choices: `tags`, `comments`, `likes`, `connection_requests`
  Make backend calls to update notification preferences when the user's preferences have changed
