### ISSUE TITLE
Loading and failure statuses [BLOCKED BY UI]

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#403]
When making API calls, we currently only render the UI component for successful cases. We should look into implementing loading and failure variations of these components in case the API call fails. An example would be when fetching a list of posts on the community page, we should have a loading indicator, and if the fetch fails, we should have some sort of error message.

**Comment by magovansh9** [comment]
App: Refactor the code to add a loading indicator when making API calls

- Update the code to add a loading indicator while fetching data for community, market, and housing posts. The user should then be directed to the following screen based on the failureStatus of the API call i.e. if the API call fails, redirect to the FailureStatus Screen else, display the list of fetched posts. Click [here](https://www.youtube.com/watch?v=scVRfoTEctcz) to view an example. Refer to the following links for more info on how to use progress indicators:- [React-Native-Progress-Indicator](https://callstack.github.io/react-native-paper/activity-indicator.html) [Material-UI-Progress-Indicator](https://material-ui.com/components/progress/). Follow the design on Figma.

App: Create a loading screen 

- Create a screen that the user is redirected to while fetching data for community, market, and housing posts. The user should then be directed to the following screen based on the failureStatus of the API call i.e. if the API call fails, redirect to the FailureStatus Screen else, display the list of fetched posts. Click [here](https://www.youtube.com/watch?v=scVRfoTEctcz) to view an example. Refer to the following links for more info on how to use progress indicators:- [React-Native-Progress-Indicator](https://callstack.github.io/react-native-paper/activity-indicator.html) [Material-UI-Progress-Indicator](https://material-ui.com/components/progress/). Follow the design on Figma.

App: Create a FailureStatus screen

- Create a screen that displays an error message as a result of a failed API call. An example would be when fetching a list of posts on the community page, we should have a loading indicator, and if the fetch fails, the user should be redirected to this screen. Follow the design on Figma.

App: Refactor the code to display an error message for failed API calls

- An example would be when fetching a list of posts on the community page, we should have a loading indicator, and if the fetch fails, an error message is displayed. Follow the design on Figma.
