### ISSUE TITLE
API: Login failure attempt limit and timeout

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#407]
We need to implement a login failure attempt limit of 5 attempts in order to mitigate brute-force cyber attacks. We also want a cool-down of 5 min before the user can try to login in again with 5 new attempts.

We can try using this package https://pypi.org/project/django-axes/1.5.0/ in our project

**Comment by bringuy** [comment]
Make sure to add the pip package to requirements.txt
