### ISSUE TITLE
Cloud-Ops: Create Back-Up File and Restore DB

### ISSUE THREAD

**Issue by adrian-salvador** [Team-uMigrate/umigrate#44]
We need to figure out how to create a database back-up file for the umigratedb database on PostgreSQL, as well as restore a database from a back-up file. We want the back-up to occur weekly.

Sub-tasks:
- Investigate the command for create back-up file
- Identify where the back-up file is located
- Investigate the command for restoring a db
- Schedule back-up weekly (test out with daily)

**Comment by adrian-salvador** [comment]
- We want a back-up file to be created for EACH time we deallocate a VM instance
     - Condition Statement of some kind?

- Refer to https://www.linode.com/docs/databases/postgresql/how-to-back-up-your-postgresql-database/

**Comment by adrian-salvador** [comment]
In the reference **https://www.postgresql.org/docs/9.1/backup.html**, 

Section **24.3.2** might be helpful

**Comment by Apsd1109** [comment]
to create a dump file:
sudo -u postgres pg_dump umigratedb > NAME_OF_FILE.sql

**Comment by Apsd1109** [comment]
sudo -u postgres psql -U postgres -d umigratedb < NAME_OF_FILE.sql
doesnt seem to work... unsure as to why

**Comment by Apsd1109** [comment]
confirmed working, auto backs up:
![image](https://user-images.githubusercontent.com/46359439/95931452-324c0e00-0d97-11eb-8506-a22c0b810975.png)
