### ISSUE TITLE
Create tickets for adding Polls and Roommate to the frontend

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#440]
Currently, we have most of the back-end done for polls and roommate posts, but we do not have them implemented in the front-end yet. We should implement these components in the front-end.

**Comment by d36mehta** [comment]
Polls ticket: https://github.com/Team-uMigrate/umigrate/issues/452
Roommate ticket: https://github.com/Team-uMigrate/umigrate/issues/470
