### ISSUE TITLE
Cloud-Ops: Setup Prod environment

### ISSUE THREAD

**Issue by adrian-salvador** [Team-uMigrate/umigrate#48]
We need to start setting up the prod environment.

Sub-task:
1. Create variable group for prod
2. Create a new VM instance in Azure for prod

**Comment by adrian-salvador** [comment]
After we restore the back up file from Storage Space onto the new server, we need to ensure network traffic is no longer on the old server.
- When completed, original server can be be deallocated, used for development, etc.

**Comment by Apsd1109** [comment]
need to change scripts to include "sudo" since we are using azure now.
