### ISSUE TITLE
Cloud-Ops: Determine what needs to be written (System Tests)

### ISSUE THREAD

**Issue by adrian-salvador** [Team-uMigrate/umigrate#54]
Research what is needed to write the Selenium tests using the Visual Studio Test Task in Azure DevOps in C#.

https://www.guru99.com/selenium-csharp-tutorial.html

**Comment by joel22b** [comment]
What needs to be done:

For each pipeline, a new agent job for the Selenium Tests. The agent job will have at least 2 tasks, the "Visual Studio Test Platform Installer" task and at least one "Visual Studio Test" task. The VS Test task will call our system tests for each release pipeline. There should be a test tab created that we can see the success of the tests. If the tests fail, the build should fail. Make sure the tests are the last agent job to be run.

Useful Resources:

Selenium Test Tutorial: https://www.guru99.com/selenium-csharp-tutorial.html
Azure Tutorial: https://azuredevopslabs.com/labs/vstsextend/selenium/
VS Test Installer: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops&viewFallbackFrom=vsts
VS Test Task: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/VsTestV2/README.md
